### ISSUE TITLE
Sketch Cloud not working. 

### ISSUE THREAD

**Issue by aliben** [duraki/SketchCrapp#13]
Hey guys, is there by any chance a way to let sketch cloud sync work ?

**Comment by duraki** [comment]
What exactly isn't working with Sketch Cloud?

**Comment by duraki** [comment]
Ok, after a bit of discussion with @elijahtsai, we figured out this is not possible right now and with-in current Sketch logic. Sometimes back in the days, I managed to crack Cloud License Manager to use generated Serial Key, but I still had to put Sketch API urls in `/etc/hosts`. Meaning, Sketch.App was never able to communicate with backend server and therefore, even when Cloud Activated, no Cloud features were available with-in Sketch.

I can leave this open if someone has any idea.

**Comment by duraki** [comment]
Since we are "overtaking" Sketch Cloud window by tagging the crackteam (see #11), I don't think this feature will be implemented anytime soon. Other than that, if you really use Sketch Cloud (ie. corporate environment), then the best thing you can do is to subscribe to Sketch and pay them some real money. I will close this for now.
