### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by stewman141** [duraki/SketchCrapp#15]
<img width="564" alt="Screen Shot 2020-08-20 at 5 45 56 PM" src="https://user-images.githubusercontent.com/69982040/90801506-e12b1b00-e30d-11ea-885b-2fc59aab4602.png">

Having this issue

**Comment by elijahtsai** [comment]
Hi, @stewman141 What version of Sketch you feed to the script? If it's in range of v63.2 ~ v68, please make sure you pass clean application to the script by clean I mean directly download from the official server and unzip and put in /Application then pass to script. without any modification.

**Comment by silviagb2** [comment]
Hi, I have the exact same issue. I had Sketch (with a crack) already installed in my laptop and I used it for a while (I have some plugins and files from sketch). After a few months using it, my mac detected a problem and I was not able to use the app again. I uninstalled it and do the process you explain from the beginning. Is it possible that the error came because of the plugins I have installed?

**Comment by elijahtsai** [comment]
Hi, @silviagb2 **First** thank you for using our script. **Second** so what version of Sketch you try to patch by using the script? I was tested on v68 and install serval plugins before I using patch script. The suggestion you say is not possible because the plugin file only installed in your library folder and Sketch only read from it. The **test result** I did **is successful**. Again please make sure you **download** the application **from Sketch official server** and **unzip the file** and **put** the Sketch.app **into /Application** then **executes the script**. Try not to open the app during the entire time before patch complete the job.

**Comment by mgleason** [comment]
`+===================================================================
+ Issue details ‹s:sketchcrapp›
+ Application Path  : /Users/xxxx/Downloads/Sketch.app
+ Application Binary: /Users/xxxx/Downloads/Sketch.app/Contents/MacOS/Sketch
+ Passed version    : ‹nil›
+ Binary SHA1       : bc22987f7b3a7580aba1ac260c59d66d0a3622e7
+ Error             : binaryerr››
+===================================================================`

**Comment by elijahtsai** [comment]
@mgleason Shifted your question to issue #16, please leave any question or message to there.

**Comment by elijahtsai** [comment]
@stewman141 and @silviagb2 Try to use our latest script again. we are looking forward to your answer 😊

**Comment by silviagb2** [comment]
Hello @elijahtsai, it works now! Thanks a lot for your work and your support. You're awesome! 😊

**Comment by elijahtsai** [comment]
@silviagb2 It's very nice to hear a positive answer, enjoy our work. 
Also, consider giving us a star at the top-right corner, it's mean a lot for us.

**Comment by elijahtsai** [comment]
We believed the problem can be resolved, closed. 
P.S. We can reopen if there has more evidence related.
